variables:
  DOCKER_HOST: tcp://docker:2375/
  APP_NAME: "zcs-web"

# docker 镜像：问运维拿适合自己项目的镜像。这个适合 node 项目
image: centos/nvm:yarn

# 将所有的 job 分为2个阶段
stages:
  - build # 构建
  # - cdn # 部署

before_script:
  - . ./ci/variables.sh # 初始化自定义变量
  - . ./ci/before-script.sh

### 下面是定义具体的 job ###

# job: 构建/编译
build:
  stage: build
  tags:
    - zcs-web_docker_1
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - $(pwd)/.yarn-cache
  script:
    - yarn install --pure-lockfile --cache-folder $(pwd)/.yarn-cache
    - . ./ci/build.sh # 打压缩包
    - . ./ci/deploy.sh # 上传到目标服务器
    - node ./ci/notify.js app=${APP_PACKAGE_NAME} message="${CI_COMMIT_MESSAGE}" user=${GITLAB_USER_LOGIN} # 通知用户发布完毕
